services:
  keycloak:
    image: jboss/keycloak:15.0.1
    ports: ['52957:8080']
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak_data:/data

volumes:
  keycloak_data: ~