home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: home/index.html.twig
    context:
      keycloakHome: '%app.keycloak_home%'

logout:
  path: /logout

openid_redirecturi:
  path: /redirect-uri
